#!/bin/sh

if [ -z $VIRTUAL_HOST ]
then
   echo "VIRTUAL_HOST is unset!"
   s6-svscanctl -q /service
fi

cat > /Caddyfile <<EOF
${VIRTUAL_HOST}

proxy / localhost:8080 {
    transparent
}
EOF

if [ ! -z $LETSENCRYPT_EMAIL ]
then
   cat >> /Caddyfile <<EOF
tls ${LETSENCRYPT_EMAIL} {
    ca $CA_URI
}
EOF
else
       echo "no TLS!"
fi


exec /usr/bin/caddy -conf /Caddyfile
